name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: public
        build_command: npm run build
